name: Pre-deployment Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_portfolio_domain: ${{ secrets.PORTFOLIO_DOMAIN }}
          TF_VAR_portfolio_subdomain: ${{ secrets.PORTFOLIO_SUBDOMAIN }}
          TF_VAR_portfolio_bucket_name: ${{ secrets.PORTFOLIO_BUCKET_NAME }}
          TF_VAR_portfolio_ssl_certificate_arn: ${{ secrets.PORTFOLIO_SSL_CERTIFICATE_ARN }}
        run: terraform plan -no-color -out=tfplan

      - name: Comment Plan on PR
        uses: marocchino/sticky-pull-request-comment@v3
        with:
          header: terraform-plan
          message: |
            ```terraform
            ${{ steps.plan.outputs.stdout }}
            ```
